version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:8.0

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}
            - v1-dependencies-

      - run: sbt compile  # Compile the Scala project

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies--{{ checksum "build.sbt" }}

      # Run your Scala tests (assuming test.scala contains your test code)
      - run: sbt "testOnly test.scala"

workflows:
  sample:
    jobs:
      - build
